services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  NITSAN\NsOpenai\:
    resource: '../Classes/*'

  NITSAN\NsOpenai\Backend\Listener\ModifyPageLayoutContent:
    tags:
      - name: event.listener
        identifier: 'nitsan/openai/modify-page-module-content'

